site_name: 动手学CSS
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Home: index.md
  - CSS:
    - 介绍: web.dev/index.md
    - 盒子模型: web.dev/box_model.md
    - 选择器: web.dev/selectors.md
    - 瀑布: web.dev/cascade.md
    - 特异性: web.dev/specificity.md
